name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache apt packages
        uses: actions/cache@v4
        with:
          path: /var/cache/apt
          key: apt-arm-gcc-${{ runner.os }}
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install -y gcc-arm-none-eabi clang-format
      - name: Generate project
        run: bash create_stm32f1_project
      - name: Format with clang-format
        run: clang-format -i main.h main.c
      - name: CodeQL Init
        uses: github/codeql-action/init@v3
        with:
          languages: cpp
      - name: Clean & rebuild for CodeQL
        run: make clean && make test
      - name: CodeQL Analyze
        uses: github/codeql-action/analyze@v3
